---

 - name: Prepare for deployment
   hosts: localhost
   tasks:

   - name: Print Hello World
     ansible.builtin.debug:
       msg: "Hello World"

   - name: Print Hello World
     ansible.builtin.debug:
       msg: "Hello {{ ansible_host }}"
