---

- name: Prepare for deployment
  hosts: all
  become: false
  gather_facts: no
  tasks:
    # - name: Bob
    #   debug:
    #     msg: "{{ hostvars }}"
    #   when: " 'ungrouped' is not in group_names"



    - name: Call My Role
      ansible.builtin.import_role:
        name: steve
