---
- name: Prepare Hosts For deployment
  hosts: localhost
  become: false
  gather_facts: no
  tasks:
    - name: Add A Host to In Memory Inventory
      ansible.builtin.add_host:
        name: '{{ survey_hostname }}'
        groups: newhosts
        foo: 42
        ansible_connection: local

- name: Do Post Deployment Stuff
  hosts: newhosts
  become: false
  gather_facts: no
  tasks:
    - name: Print the value of foo
      ansible.builtin.debug:
        var: foo
