---
# env['VMWARE_USER'] = cred.get_input('username', default='')
# env['VMWARE_PASSWORD'] = cred.get_input('password', default='')
# env['VMWARE_HOST'] = cred.get_input('host', default='')
# env['VMWARE_VALIDATE_CERTS'] = str(settings.VMWARE_VALIDATE_CERTS)

# - name: Print Secret Stuff
#   ansible.builtin.debug:
#     msg: "{{ lookup('env','VMWARE_USER')}} {{ lookup('env','VMWARE_PASSWORD')}}"

# CURL Command:
# curl --location --request POST 'https://<vRA8.1-URL>/csp/gateway/am/api/login?access_token' \
# --header 'Content-Type: application/json' \
# --data-raw '{
# 	"username": "username",
# 	"password": "password",
# 	"domain": "System Domain | AD Domain"
# }' | tojson
- name: Call a URI
  no_log: global_no_log | default(true)
  ansible.builtin.uri:
    url: "https://VRA/csp/gateway/am/api/login?access_token"
    method: POST
    body_format: json
    body:
      username: "{{ lookup('env','VMWARE_USER') }}"
      password: "{{ lookup('env','VMWARE_USER') }}"
      domain: "{{ vmware_domain | default('Something') }}"
    register: vra_access_token_request

- name: Extract token
  set_fact:
    vra_access_token: "{{ vra_access_token_request.json['access_token']}}"

- name: Do something fun
  ansible.builtin.uri:
    url: "https://VRA/deployment/api/deployments/{{ deployment_id }}?expandResources=true"
    headers:
      Authorization: "Bearer {{ vra_access_token }}"
  register: output

  # print output here, I'm not going to type it again
  
