---
- name: Setup Credentials for Oracle
  no_log: true
  ansible.builtin.set_fact:
      ora_username: "{{ lookup('env','VMWARE_USER') }}"
      ora_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
      ora_hostname: "{{  lookup('env','VMWARE_HOST') }}"
      ora_sid: ORCL
      fruit: "{{ ['apple','pear','banana','strawberry'] | random}}"
      number: "{{ range(100) | random }}"

- name: Insert a row
    hostname: "{{ ora_hostname }}"
    username: "{{ ora_username }}"
    password: "{{ ora_password }}"
    service_name: "{{ ora_sid }}"
    sql: "INSERT INTO test VALUES({{number},'{{fruit}}'})"

- name: Get the table data
  ari_stark.ansible_oracle_modules.oracle_sql:
    hostname: "{{ ora_hostname }}"
    username: "{{ ora_username }}"
    password: "{{ ora_password }}"
    service_name: "{{ ora_sid }}"
    sql: "SELECT * FROM test"

  register: ora_out

- name: Print Results
  ansible.builtin.debug:
    var: ora_out

