---

- name: Call the make a website task for each website
  include_tasks:
    file: "notapache.yml"
  vars:
    server_name: "{{ ext_item[0] }}"
    server_settings: "{{ ext_item[1] }}"
  loop: "{{ websites | items }}"
  loop_control:
    loop_var: ext_item

# - name: Debug websites by item
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop: "{{ websites | items }}"

# - name: Debug websites
#   ansible.builtin.debug:
#     var: websites


# - ansible.builtin.shell: "roles/steve/scripts/important.py"
#   delegate_to: "{{ loadbalancer }}"
#   register: myvar
#   run_once: true

# - name: Set backup time
#   ansible.builtin.set_fact:
#     backuptime: "{{ lookup('pipe','date') }}"
#   run_once: true   

# - name: Debug myvar
#   ansible.builtin.debug:
#     var: backuptime

# # - name: Set load balancer variables
# #   ansible.builtin.set_fact:
# #     iplist: "{{ (iplist | default([])) + [ hostvars[item]['fakeip'] ] }}"
# #   loop: "{{ groups['webservers'] }}" 
# #   when: "'loadbalancer' is in group_names"


# # - name: Set facts with delegate
# #   ansible.builtin.set_fact:
# #     lb_ip: "{{ fakeip }}"
# #   delegate_to: "{{ item }}"
# #   delegate_facts: true
# #   loop: "{{ groups['webservers']}}"
# #   when: "'loadbalancer' is in group_names"

# # - name: Debug lb_ip
# #   ansible.builtin.debug:
# #     var: lb_ip

  